### ISSUE TITLE
需要将图片迁移至图床

### ISSUE THREAD

**Issue by Lazarus-glhf** [lab530/lab530.github.io.bak#26]

**Comment by Yestercafe** [comment]
暂时不修，没有更好的方案

**Comment by Yestercafe** [comment]
找到新方法了，尝试修复

**Comment by Lazarus-glhf** [comment]
目前找不到能兼顾速度与安全的解决方法，现决定将图片统一迁移至/lab530/assets_images_storage 中，请按照新上传的文章"PicGo-配置教程及博客图片上传规范"完成操作。同志们，开始搬屎山了🤗🤗🤗🤗。 @dengyueW @ErefIect @Hanpro9 @
